- name: create ansible5 user
  user:
    name: ansible5
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible5
    owner: root
    group: root
    mode: 0440
